[models]

[models.gpt-4o.personal]
name = "Personal"
token = "sk-openai-personal"

[models.gpt-4o.company]
name = "Company"
token = "sk-openai-company"

[models.claude-3-5.personal]
name = "Personal"
token = "sk-anthropic-personal" 