# ==================================================
# Model Configurations
# ==================================================
[models]
# --------------------------------------------------
# ModelScope Configuration
# --------------------------------------------------
[models.modelscope]
description = "ModelScope 配置"
name = "ModelScope"
# --------------------------------------------------
# ModelScope Accounts Configuration
# --------------------------------------------------
[models.modelscope.accounts]
[models.modelscope.accounts.personal]
name = "个人账号"
token = "ms-xxx"
[models.modelscope.accounts.company]
name = "公司账号"
token = "ms-yyy"
# --------------------------------------------------
# ModelScope Products Configuration
# --------------------------------------------------
[models.modelscope.products]
[models.modelscope.products.claude_code]
name = "Claude Code"
description = "ModelScope 针对 claude_code 需要配置的环境变量"
token_field = "ANTHROPIC_AUTH_TOKEN"
[models.modelscope.products.claude_code.default_config]
ANTHROPIC_BASE_URL = "https://api-inference.modelscope.cn"
ANTHROPIC_SMALL_FAST_MODEL = "Qwen/Qwen3-Coder-480B-A35B-Instruct"
ANTHROPIC_MODEL = "Qwen/Qwen3-Coder-480B-A35B-Instruct"
[models.modelscope.products.codex]
name = "Codex"
description = "ModelScope 针对 codex 需要配置的环境变量"
token_field = "CODEX_AUTH_TOKEN"
[models.modelscope.products.codex.default_config]
CODEX_BASE_URL = "https://api-inference.modelscope.cn"
CODEX_MODEL = "Qwen/Qwen3-Coder-480B-A35B-Instruct"

